---
# tasks file for windows-exporter
- name: Check for windows exporter agent service...
  win_service:
    name: "windows_exporter"
  register: svc

- block:
  - name: Set fact install variable for Hyper-V
    set_fact:
      collectors: 'ENABLED_COLLECTORS=[defaults],hyperv'
    when: "'hyperv' in group_names"    

  - name: Create Windows Exporter folders as needed...
    win_file:
      path: '{{ win_exporter_temp_dir }}'
      state: directory

  - name: Copy Windows Exporter  archive...
    win_get_url:
      url:  '{{ win_exporter_download_link }}'
      dest: '{{ win_exporter_temp_dir }}'
      timeout: 300

  - name: Windows Exporter agent installation...
    win_dsc:
      resource_name: package
      Name: "windows_exporter"
      Path: '{{ win_exporter_temp_dir }}\{{ win_exporter_package_name }}'
      Arguments: '{{ collectors }}'
      ProductId: '287A67BF-0D4D-4DB2-AB1D-97EB8A098C29'
      Ensure: Present
    register: result
    retries: 3
    delay: 60
  
  - name: Verify the Windows Exporter service...
    win_service:
      name: "windows_exporter"
      state: started
    register: svc_2


  - debug:
      msg: "Qualys setup exited with code: {{ result.rc }}."

  when: svc.exists == false
