---
# defaults file for deploy_mssql
# SQL version 14
#win_mssql_engine_action_install:            'install'
#win_mssql_engine_action_configure:          'configure'
win_mssql_engine_action:                    'install'

win_mssql_engine_instance_name:             'MSSQLSERVER'
win_mssql_engine_server_name:               '{{ inventory_hostname }}'

win_mssql_engine_features:                  'SQLENGINE,CONN'
win_mssql_engine_collation:                 'SQL_Latin1_General_CP1_CI_AS' 

win_mssql_engine_temp_dir:                  'C:\Temp'

win_mssql_engine_install_shared_dir:        'C:\Program Files\Microsoft SQL Server'
win_mssql_engine_install_shared_wow_dir:    'C:\Program Files (x86)\Microsoft SQL Server'

win_mssql_engine_instance_dir:              'C:\Program Files\Microsoft SQL Server'
win_mssql_engine_sql_data_dir:              'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\Data'
win_mssql_engine_sql_user_db_dir:           '{{ win_mssql_engine_sql_data_dir }}'
win_mssql_engine_sql_user_db_log_dir:       '{{ win_mssql_engine_sql_data_dir }}'
win_mssql_engine_sql_temp_db_dir:           '{{ win_mssql_engine_sql_data_dir }}'
win_mssql_engine_sql_temp_db_log_dir:       '{{ win_mssql_engine_sql_data_dir }}'
win_mssql_engine_backup_dir:                'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\Backup'

win_mssql_engine_install_log:               'C:\Program Files\Microsoft SQL Server\140\Setup Bootstrap\Log\Summary.txt'

win_mssql_engine_update_enabled:            false
win_mssql_engine_browser_startup_type:      'Automatic'

win_mssql_engine_install_management_studio: false

win_mssql_engine_engine_service_account:    '{{ dns_domain_name }}\sql-svc'
win_mssql_engine_system_admins:             '{{ dns_domain_name }}\sql-admins'